### ISSUE TITLE
撤单代码 历史遗留问题

### ISSUE THREAD

**Issue by Laotouy** [WoSai/shouqianba-webapi-javademo#6]
在 

https://github.com/WoSai/shouqianba-webapi-javademo/commit/40c9f83a7bfef331ecc68acc270cf67bd40fc056#diff-7978e362796fb5feef7d1921fb7938fbc8a276808c51f1d5a37f4b28d1012557

 提交中 把 HttpProxy 中的 revoke 扯淡方法删除了
但是没有在 Main 类中删除这个测试调用的方法

**Comment by jacexh** [comment]
已修复
